on:
  push:
    branches:
      - main
    paths:
      - package.json
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      # Checkout the repository
      - uses: actions/checkout@v4
  
      # Create a new version tag
      - uses: Klemensas/action-autotag@stable
        id: tag
        with:
          tag_prefix: v
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create the changelog
      - uses: heinrichreimer/action-github-changelog-generator@v2.3
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Extract the release notes
      - uses: actions-ecosystem/action-regex-match@v2
        id: releasenotes
        with:
          text: ${{ steps.changelog.outputs.changelog }}
          regex: ^(\n|.)*?(##(.+)\n\n((\n|.)*?))(\n)+(##(\n|.)*)?(\n)+\\\*(.+)$

      # Create a new GitHub release
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tagname }}
          body: ${{ steps.releasenotes.outputs.group4 }}

      # Publish a new NPM version
      - uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}